apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: nginx-image
          image: nginx    # Use the desired Docker Registry image
          ports:
            - containerPort: 5000

