apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort   # Change this to LoadBalancer if available, or ClusterIP for internal-only access
 